company/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('<int:pk>/', views.detail, name='detail'),
]

home/models.py
from django.db import models

# Create your models here.
class Newsletter(models.Model):
    email = models.EmailField()
    def __str__(self):
        return self.email+" added in the list."

class Contact(models.Model):
    name = models.CharField(max_length= 30)
    email= models.EmailField()
    subject = models.CharField(max_length = 100)
    message = models.TextField()

    def __str__(self):
        return "Query made by "+ self.name


class Project(models.Model):
    category = models.CharField(max_length= 50)
    client = models.CharField(max_length= 50)
    images = models.ImageField(upload_to='home/images', default='')
    date = models.DateTimeField(auto_now_add=True)
    link = models.URLField()
    title = models.CharField(max_length= 150)
    desc = models.TextField()
    tag = models.CharField(max_length= 30)
    def __str__(self):
        return self.title


class Image(models.Model):
    project = models.ForeignKey(Project, on_delete= models.CASCADE)
    image = models.ImageField(upload_to='home/images', default='')
    def __str__(self):
        return 'Some image added'
    
    

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Project, Contact, Newsletter, Image

# Create your views here.
def index(request):
    projects = Project.objects.all()
    context = {
        'projects' : projects,
    }
    return render(request, 'home/index.html', context)


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        ref = Contact(name = name, email = email, subject = subject, message = message)
        messages.success(request, 'Your message has been succesfully recieved by us. We will contact you ASAP!!')
        ref.save()
    return redirect('/')

def newsletter(request):
    if request.method == 'POST':
        email = request.POST['email']
        ref = Newsletter(email = email)
        ref.save()
        messages.success(request, 'You have been succesfully added to the list!!')
    return redirect('/')


def detail(request, pk):
    project = Project.objects.filter(pk = pk).first()
    context = {
        'project' : project,
    }
    return render(request, 'home/portfolio-details.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>JReady</title>
  <meta content="Become Job Ready" name="descriptison">
  <meta content="Jready" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'home/img/favicon.png' %}" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'home/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'home/css/style.css' %}" rel="stylesheet" type='text/css'>
</head>

<body>
  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-none d-lg-block">
    <div class="container clearfix">
      <div class="contact-info float-left">
        <i class="icofont-envelope"></i><a href="mailto:contact@example.com">jindalsaurabh533@gmail.com</a>
        <i class="icofont-phone"></i> +91 - 8860697807
      </div>
      <div class="social-links float-right">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="skype"><i class="icofont-skype"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container">

      <div class="logo float-left">
        <h1 class="text-light"><a href="{% url 'index' %}"><span>JReady</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'index' %}">Home</a></li>
          <li><a href="#about">About Us</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li>
          <li><a href="#contact">Contact Us</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->
{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible mb-0 fade show" role="alert">
  <strong>Message : </strong> {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
{% endfor %}
{% block body %}

{% endblock body %}

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>JReady</h3>
            <p>
              Canaught Palace Street <br>
              New Delhi, India<br><br>
              <strong>Phone:</strong> +91 - 8860697807<br>
              <strong>Email:</strong> jindalsaurabh533@gmail.com<br>
            </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#about">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#services">Services</a></li>
              {% comment %} <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li> {% endcomment %}
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Be a part of authentic Newsletter that give you wings.</p>
            <form action="{% url 'newsletter' %}" method="POST">
              {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'home/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'home/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'home/vendor/jquery-sticky/jquery.sticky.js' %}"></script>
  <script src="{% static 'home/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'home/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'home/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'home/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'home/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'home/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'home/js/main.js' %}"></script>

</body>

</html>

templates/home/inner-page.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<main id="main">

  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Inner Page</h2>
        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Inner Page</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs Section -->

  <section class="inner-page">
    <div class="container">
      <p>
        Example inner page template
      </p>
    </div>
  </section>

</main><!-- End #main -->
{% endblock body %}

  

templates/home/portfolio-details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<main id="main">

  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Project Details</h2>
        <ol>
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="portfolio.html">Portfolio</a></li>
          <li>Portfolio Details</li>
        </ol>
      </div>

    </div>
  </section><!-- Breadcrumbs Section -->

  <!-- ======= Portfolio Details Section ======= -->
  <section class="portfolio-details">
    <div class="container">

      <div class="portfolio-details-container">

        <div class="owl-carousel portfolio-details-carousel">
          {% for image in project.image_set.all %}
          <img src="{{ image.url }}" class="img-fluid" alt="Project Images">
          {% endfor %}
        </div>

        <div class="portfolio-info">
          <h3>Project information</h3>
          <ul>
            <li><strong>Category</strong>: {{ project.category }}</li>
            <li><strong>Client</strong>: {{ project.client }}</li>
            <li><strong>Project date</strong>: {{ project.date|date }}</li>
            <li><strong>Project URL</strong>: <a href="{{ project.link }}">{{ project.link }}</a></li>
          </ul>
        </div>
      </div>

      <div class="portfolio-description">
        <h2>{{ project.title }}</h2>
        <p>
          {{ project.desc|safe }}
        </p>
      </div>
    </div>
  </section><!-- End Portfolio Details Section -->

</main><!-- End #main -->
{% endblock body %}